export const SET_CATALOG = 'root/SET_CATALOG'
export const SET_CURRENT_PAGE = 'root/SET_CURRENT_PAGE'
export const ADD_TO_CART = 'root/ADD_TO_CART'
export const REMOVE_FROM_CARD = 'root/REMOVE_FROM_CARD'
export const SET_QUERY = 'root/SET_QUERY'
